// Generated by CoffeeScript 1.6.1
/*
localHistory = [{author:'system', text:'Welcome to chat'}]
mylines = localHistory 
addEventListener('message', (e) -> connection.send(e))
*/

var acceptNick, addLine, connection, refuseNick, roomList, sendJSON, setHistory, setNick, viewers;

connection = new WebSocket('ws://127.0.0.1:8088');

connection.setSetUsers = function(u) {
  return connection.setUsers = u;
};

connection.setAddHistoryLine = function(f) {
  return connection.addHistory = f;
};

connection.setChooseNick = function(f) {
  return connection.chooseNick = f;
};

connection.setGetRooms = function(f) {
  return connection.getRooms = f;
};

connection.onopen = function() {};

connection.onerror = function(error) {};

sendJSON = function(type, data) {
  var obj;
  obj = {
    type: type,
    data: data
  };
  return connection.send(JSON.stringify(obj));
};

connection.requestHandle = function(handle) {
  return sendJSON('handle', handle);
};

connection.requestRoomList = function(roomName) {
  return sendJSON('listRooms', '');
};

connection.joinRoom = function(roomName) {
  return sendJSON('join', roomName);
};

connection.requestRoom = function(roomName) {
  return sendJSON('room', roomName);
};

connection.sendMessage = function(message) {
  return sendJSON('message', message);
};

connection.onmessage = function(message) {
  var e, json;
  try {
    json = JSON.parse(message.data);
  } catch (_error) {
    e = _error;
    console.log('This doesn\'t look like a valid JSON: ', message.data);
  }
  if (json.type === 'history') {
    setHistory(json.data);
  }
  if (json.type === 'message') {
    addLine(json.data);
  }
  if (json.type === 'acceptNickname') {
    acceptNick(json.data);
  }
  if (json.type === 'refuseNickname') {
    refuseNick(json.data);
  }
  if (json.type === 'roomList') {
    roomList(json.data);
  }
  if (json.type === 'viewers') {
    return viewers(json.data);
  }
};

viewers = function(data) {
  return connection.setUsers(data);
};

setHistory = function(history) {};

addLine = function(line) {
  console.log(line);
  return connection.addHistory(line);
};

setNick = function(nick) {
  window.localStorage.setItem('nick', nick);
  return connection.chooseNick(nick);
};

acceptNick = function(nick) {
  console.log('accept ', nick);
  return setNick(nick);
};

refuseNick = function(nick) {
  var nonick;
  console.log('refuse ', nick);
  nonick = '(' + nick + ')';
  return setNick(nonick);
};

roomList = function(list) {
  console.log('Rooms: ', list);
  return connection.getRooms(list);
};
