// Generated by CoffeeScript 1.6.1
var acceptNick, addLine, connection, refuseNick, setHistory;

window.WebSocket = window.WebSocket;

localStorage.history = '';

addEventListener('message', function(e) {
  return connection.send(e);
});

connection = new WebSocket('ws://127.0.0.1:1337');

connection.onopen = function() {};

connection.onerror = function(error) {};

connection.requestHandle = function(handle) {
  return connection.send(handle);
};

connection.requestRoom = function(roomName) {
  return connection.send(roomName);
};

connection.sendMessage = function(message) {
  return connection.send(message);
};

connection.onmessage = function(message) {
  var e, json;
  try {
    json = JSON.parse(message.data);
  } catch (_error) {
    e = _error;
    console.log('This doesn\'t look like a valid JSON: ', message.data);
  }
  if (json.type === 'history') {
    setHistory(json.data);
  }
  if (json.type === 'message') {
    addLine(json.data);
  }
  if (json.type === 'acceptNickname') {
    acceptNick(json.data);
  }
  if (json.type === 'refuseNickname') {
    return refuseNick(json.data);
  }
};

setHistory = function(history) {
  var line, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = history.length; _i < _len; _i++) {
    line = history[_i];
    _results.push(console.log(line));
  }
  return _results;
};

addLine = function(line) {
  console.log(line);
  localStorage.history = localStorage.history || '';
  return localStorage.history = localStorage.history + line.text;
};

acceptNick = function(nick) {
  console.log('accept ', nick);
  return sessionStorage.nickName = nick;
};

refuseNick = function(nick) {
  console.log('refuse ', nick);
  return sessionStorage.nickName = '';
};
