// Generated by CoffeeScript 1.6.1

uChat.service('chatModel', function() {
  connection.setAddHistoryLine(function(l) {
    return this.addLine(l);
  });
  this.getNickName = function() {
    return window.localStorage.getItem('nick');
  };
  this.getHistory = function() {
    var history, saved;
    saved = window.localStorage.getItem('history' || JSON.stringify([]));
    if (saved.length === 0) {
      saved = JSON.stringify([]);
    }
    history = JSON.parse(saved);
    if (history) {
      return history;
    }
    return [];
  };
  return this.addLine = function(line) {
    var history;
    history = this.getHistory();
    history.unshift(line);
    window.localStorage.setItem('history', JSON.stringify(history));
    return history;
  };
});
