// Generated by CoffeeScript 1.6.1

uChat.service('chatModel', function() {
  connection.setAddHistoryLine(function(l) {
    return this.addLine(l);
  });
  this.getNickName = function() {
    return window.localStorage.getItem('nick');
  };
  this.getHistory = function() {
    var history;
    history = JSON.parse(window.localStorage.getItem('history'));
    if (history) {
      return history;
    }
    return [];
  };
  return this.addLine = function(line) {
    var history;
    history = this.getHistory();
    history.push(line);
    return window.localStorage.setItem('history', JSON.stringify(chapter));
  };
});
