// Generated by CoffeeScript 1.6.1

uChat.service('loginModel', function() {
  localStorage.nickName = 'MyFineNick';
  this.getNickName = function() {
    return localStorage.nickName || '#NoNickNameRegistered#';
  };
  return this.getHistory = function() {
    return localStorage.history || '...';
  };
});
