// Generated by CoffeeScript 1.6.1
(function() {

  window.myController = function($scope) {
    $scope.title = "MyTitle";
    $scope.todo = [
      {
        job: "Stuffing",
        done: false
      }, {
        job: "more",
        done: true
      }, {
        job: "Learn Angular",
        done: false
      }
    ];
    return $scope.two = function() {
      return [
        {
          job: "more",
          done: true
        }, {
          job: "Learn Angular",
          done: false
        }
      ];
    };
  };

}).call(this);
