// Generated by CoffeeScript 1.6.1
(function() {

  window.myController = function($scope) {
    $scope.title = "MyTitle";
    $scope.todo = [
      {
        job: "Stuffing",
        done: false
      }, {
        job: "more",
        done: true
      }, {
        job: "Learn Angular",
        done: false
      }
    ];
    return 1;
  };

}).call(this);
