// Generated by CoffeeScript 1.6.1

uChat.controller('chatController', function($scope, $location, $routeParams) {
  if ($scope.history === void 0) {
    $scope.history = [
      {
        author: 'system',
        text: 'Welcome'
      }
    ];
  }
  connection.setAddHistoryLine(function(l) {});
  return $scope.sendMessage = function() {
    connection.sendMessage($scope.chat.message);
    $scope.history = localStorage.history;
    return $location.path('/chat/');
  };
});
