// Generated by CoffeeScript 1.6.1

uChat.controller('chatController', function($scope, $location, $routeParams) {
  $scope.history = [
    {
      author: 'system',
      text: 'Welcome'
    }
  ];
  connection.setAddHistoryLine(function(l) {
    return $scope.history.push(l);
  });
  return $scope.sendMessage = function() {
    connection.sendMessage($scope.chat.message);
    $scope.history = localStorage.history;
    return $location.path('/chat/');
  };
});
