// Generated by CoffeeScript 1.6.1

uChat.controller('loginController', function($scope, $location, $routeParams, chatModel) {
  $scope.chooseHandle = function() {
    connection.requestHandle($scope.login.handle);
    return $location.path('/chat/');
  };
  $scope.createRoom = function() {
    connection.requestRoom($scope.login.roomName);
    return $location.path('/chat/');
  };
  return 1;
});
