// Generated by CoffeeScript 1.6.1

uChat.controller('loginController', function($scope, $location, $routeParams) {
  $scope.chooseHandle = function() {
    connection.requesthandle($scope.login.handle);
    return $location.path('/chatsAvailable/');
  };
  $scope.createRoom = function() {
    return $location.path('/chat/');
  };
  $scope.sendMessage = function() {
    $route.chat.message = '';
    return $location.path('/chat/');
  };
  return 1;
});
